source "https://rubygems.org"

gem "rake", "12.3.0"
gem "concurrent-ruby", "1.0.5"
gem "i18n", "0.9.3"
gem "minitest", "5.11.3"
gem "tzinfo", "1.2.5"
gem "sinatra"
gem "sinatra-contrib"
gem "encrypted_strings"
gem "activesupport"
gem "dotenv"
gem "httparty"
gem "rspec"
gem "climate_control"
