source "https://rubygems.org"

gem "rake", "12.3.0"
gem "concurrent-ruby", "1.0.5"
gem "sinatra"
gem "sinatra-contrib"
gem "encrypted_strings"
gem "activesupport"
gem "dotenv"
gem "httparty"
gem "rspec"
gem "climate_control"
